Import('env')

# Set paths
build = env['CONFIG']['global']['build']['paper']
source = env['CONFIG']['global']['source']['paper']

# Specify Targets
env.BuildLatex(
    target=['#{}paper_template.pdf'.format(build)],
    source=[
        f'#{source}paper_template.tex',
        # Subfiles
        f'#{source}subfiles/abstract.tex',
        f'#{source}subfiles/introduction.tex',
        f'#{source}subfiles/appendix_template.tex',
    ],
    log_ext='paper_template',
    chdir=source,
    rel_path = True  # Builder can't see `chdir`, so we indicate its use here
)

# Install Targets to Release
env.Install('#release', '#{}'.format(build))