Import('env')

# Set paths
build = env['CONFIG']['global']['build']['paper']
source = env['CONFIG']['global']['source']['paper']
input = env['CONFIG']['global']['input']
raw = env['CONFIG']['global']['source']['raw']

# Specify Targets
env.BuildLatex(
    target=['#{}paper_template.pdf'.format(build)],
    source=[
        f'#{source}paper_template.tex',
        # Subfiles
        f'#{source}subfiles/abstract.tex',
        f'#{source}subfiles/introduction.tex',
        f'#{source}subfiles/appendix_template.tex',
        # Figures
        f'#{input}descriptive/plot.pdf',
        # Tables
        f'#{input}descriptive/table.txt',
        # References
        f'#{raw}references/references.bib',
        f'#{raw}references/jpe.bst',
    ],
    log_ext='paper_template',
    chdir=source,
    rel_path = True  # Builder can't see `chdir`, so we indicate its use here
)

# Install Targets to Release
env.Install('#release', '#{}'.format(build))