Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['prepare_data']
source = env['CONFIG']['global']['source']['prepare_data']

env.BuildPython(
    target = [f'#{build}/data.txt'],
    source = [f'#{source}/create_data.py'],
    log_ext =  'create_data'
)

# env.BuildStata(
#     target = [f'#{build}/data.txt'],
#     source = [f'#{source}/create_data.do'],
#     log_ext = 'create_data'
# )

# env.BuildR(
#     target = [f'#{build}/data.txt'],
#     source = [f'#{source}/create_data.r'],
#     log_ext = 'create_data'
# )

# env.BuildMatlab(
#     target = [f'#{build}/data.txt'],
#     source = [f'#{source}/create_data.m'],
#     log_ext = 'create_data'
# )

# # Invalid syntax for Windows.
# gs.build_anything(
#     target = [f'#{build}/data.txt'],
#     source = [''],
#     action = 'sh source/prepare_data/create_data.sh',
#     log_ext = 'create_data',
#     env = env
# )

env.Install('#release/lg', f'#{build}/data.txt')
