Import('env')

build = env['CONFIG']['global']['build']['descriptive']
source = env['CONFIG']['global']['source']['descriptive']
data = env['CONFIG']['global']['build']['prepare_data']

env.BuildPython(
    target = [
        f'#{build}/plot.eps',
        f'#{build}/table.txt'
    ],
    source = [
        f'#{source}/descriptive.py',
        f'#{data}/data.txt'
    ],
    log_ext = 'descriptive'
)

env.Install('#release', f'#{build}/')
